# Generated by Django 5.2.1 on 2025-05-27 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='authority_level',
            field=models.IntegerField(choices=[(1, 'Admin'), (2, 'Staff'), (3, 'Worker')], default=3),
        ),
    ]
