# Generated by Django 5.2.1 on 2025-05-30 11:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_customuser_authority_level'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SalaryRecord',
            new_name='OperatorSalary',
        ),
        migrations.AddField(
            model_name='operator',
            name='registration_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterUniqueTogether(
            name='operatorsalary',
            unique_together={('operator', 'month', 'year')},
        ),
    ]
