# Generated by Django 5.2.1 on 2025-05-31 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_salaryrecord_operatorsalary_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenancerecord',
            name='amount_spent',
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='description',
            field=models.TextField(default='hello'),
        ),
        migrations.AlterField(
            model_name='operator',
            name='registration_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
