# Generated by Django 5.2.1 on 2025-07-11 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_maintenancerecord_amount_spent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancerecord',
            name='bill_file',
            field=models.FileField(blank=True, null=True,
                                   upload_to='maintenance_bills/'),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='description',
            field=models.TextField(),
        ),
    ]
