# Generated by Django 5.2.3 on 2025-07-14 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_maintenancerecord_bill_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='papers',
        ),
        migrations.AddField(
            model_name='machine',
            name='assigned_site',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='chassis_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='engine_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='fitness_cert',
            field=models.FileField(blank=True, null=True, upload_to='machine_docs/'),
        ),
        migrations.AddField(
            model_name='machine',
            name='fitness_cert_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='fitness_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='fuel_capacity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='fuel_consumption',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='fuel_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='insurance_copy',
            field=models.FileField(blank=True, null=True, upload_to='machine_docs/'),
        ),
        migrations.AddField(
            model_name='machine',
            name='insurance_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='insurance_policy_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='insurance_provider',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='machine_photo',
            field=models.FileField(blank=True, null=True, upload_to='machine_docs/'),
        ),
        migrations.AddField(
            model_name='machine',
            name='machine_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='manufacturing_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='owner_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='owner_contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='owner_id',
            field=models.FileField(blank=True, null=True, upload_to='machine_docs/'),
        ),
        migrations.AddField(
            model_name='machine',
            name='owner_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='owner_photo_id',
            field=models.FileField(blank=True, null=True, upload_to='machine_docs/'),
        ),
        migrations.AddField(
            model_name='machine',
            name='permit_doc',
            field=models.FileField(blank=True, null=True, upload_to='machine_docs/'),
        ),
        migrations.AddField(
            model_name='machine',
            name='permit_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='permit_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='pollution_cert',
            field=models.FileField(blank=True, null=True, upload_to='machine_docs/'),
        ),
        migrations.AddField(
            model_name='machine',
            name='pollution_cert_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='pollution_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='rc_book_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='rc_upload',
            field=models.FileField(blank=True, null=True, upload_to='machine_docs/'),
        ),
        migrations.AddField(
            model_name='machine',
            name='road_tax_validity',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='working_hours',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
