# Generated by Django 5.2.3 on 2025-07-15 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_machine_papers_machine_assigned_site_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='registration_date',
        ),
    ]
